package com.nicolag.accessibilitydemo.ui

import android.arch.lifecycle.Observer
import android.os.Bundle
import android.support.design.widget.NavigationView
import android.support.v4.view.GravityCompat
import android.support.v7.app.ActionBarDrawerToggle
import android.support.v7.app.AppCompatActivity
import android.view.MenuItem
import com.nicolag.accessibilitydemo.R
import com.nicolag.accessibilitydemo.injection.App
import com.nicolag.accessibilitydemo.ui.view.*
import com.nicolag.accessibilitydemo.viewmodel.MainViewModel
import kotlinx.android.synthetic.main.activity_main.*
import kotlinx.android.synthetic.main.app_bar_main.*
import javax.inject.Inject

/**
 * Main Activity - launches on app launch. A majority is boilerplate generated by Android Studio.
 */
class MainActivity : AppCompatActivity(), NavigationView.OnNavigationItemSelectedListener {

    @Inject
    lateinit var viewModelFactory: MainViewModel.MainViewModelFactory

    private val viewModel: MainViewModel by lazy {
        viewModelFactory.getViewModel(this)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        injectActivity()

        setContentView(R.layout.activity_main)
        setSupportActionBar(toolbar)

        val toggle = ActionBarDrawerToggle(
            this, drawer_layout, toolbar,
            R.string.navigation_drawer_open,
            R.string.navigation_drawer_close
        )
        drawer_layout.addDrawerListener(toggle)
        toggle.syncState()

        nav_view.setNavigationItemSelectedListener(this)

        observeViewModel()

        viewModel.dispatch(Action.Load)
    }

    override fun onBackPressed() {
        if (drawer_layout.isDrawerOpen(GravityCompat.START)) {
            closeDrawer()
        } else {
            super.onBackPressed()
        }
    }

    override fun onNavigationItemSelected(item: MenuItem): Boolean {
        // Handle navigation view item clicks here.
        when (item.itemId) {
            R.id.nav_home -> viewModel.dispatch(Action.NavItemClick(NavItem.Home))
            R.id.nav_buttons -> viewModel.dispatch(Action.NavItemClick(NavItem.Buttons))
            R.id.nav_tabs -> viewModel.dispatch(Action.NavItemClick(NavItem.Tabs))
            R.id.nav_rating -> viewModel.dispatch(Action.NavItemClick(NavItem.RatingBar))
            R.id.nav_list -> viewModel.dispatch(Action.NavItemClick(NavItem.ListView))
            R.id.nav_search -> viewModel.dispatch(Action.NavItemClick(NavItem.Search))
            R.id.nav_links -> viewModel.dispatch(Action.NavItemClick(NavItem.Links))
            R.id.nav_text -> viewModel.dispatch(Action.NavItemClick(NavItem.OtherText))
            R.id.nav_layout -> viewModel.dispatch(Action.NavItemClick(NavItem.Layout))
        }
        closeDrawer()
        return true
    }

    private fun closeDrawer() {
        drawer_layout.closeDrawer(GravityCompat.START)
    }

    private fun observeViewModel() {
        viewModel.state().observe(this, Observer<MainViewModel.State> { state ->
            state?.let { renderViewState(it) }
        })
        viewModel.event().observe(this, Observer<MainViewModel.Event> {
            renderViewEvent(it)
        })
    }

    private fun renderViewState(state: MainViewModel.State) {
        val fragmentTransaction = supportFragmentManager.beginTransaction()
        val fragment = when (state.navItem) {
            is NavItem.Home -> HomeFragment()
            is NavItem.Buttons -> ButtonsFragment()
            is NavItem.Tabs -> TabsFragment()
            is NavItem.RatingBar -> RatingBarFragment()
            is NavItem.ListView -> ListViewFragment()
            is NavItem.Search -> SearchFragment()
            is NavItem.Links -> LinksFragment()
            is NavItem.OtherText -> OtherTextFragment()
            is NavItem.Layout -> LayoutFragment()
        }

        fragmentTransaction.replace(R.id.content_fragment, fragment, state.navItem.toString())
        fragmentTransaction.commit()
    }

    private fun renderViewEvent(event: MainViewModel.Event?) {
        when (event) {
            is MainViewModel.Event.CloseNavDrawer -> {
                closeDrawer()
            }
        }
    }

    private fun injectActivity() {
        App.appComponent.inject(this)
    }

    sealed class Action {
        object Load : Action()
        class NavItemClick(val item: NavItem) : Action()
    }

    sealed class NavItem {
        object Home : NavItem()
        object Buttons : NavItem()
        object Tabs : NavItem()
        object RatingBar : NavItem()
        object ListView : NavItem()
        object Search : NavItem()
        object Links : NavItem()
        object OtherText : NavItem()
        object Layout : NavItem()
    }
}