package com.nicolag.accessibilitydemo.ui

import android.arch.lifecycle.Observer
import android.os.Bundle
import android.support.design.widget.NavigationView
import android.support.v4.view.GravityCompat
import android.support.v7.app.ActionBarDrawerToggle
import android.support.v7.app.AppCompatActivity
import android.view.Menu
import android.view.MenuItem
import com.nicolag.accessibilitydemo.R
import com.nicolag.accessibilitydemo.injection.App
import com.nicolag.accessibilitydemo.ui.view.HomeFragment
import com.nicolag.accessibilitydemo.ui.view.TabsFragment
import com.nicolag.accessibilitydemo.viewmodel.MainViewModel
import kotlinx.android.synthetic.main.activity_main.*
import kotlinx.android.synthetic.main.app_bar_main.*
import javax.inject.Inject

/**
 * Main Activity - launches on app launch. A majority is boilerplate generated by Android Studio.
 */
class MainActivity : AppCompatActivity(), NavigationView.OnNavigationItemSelectedListener {

    @Inject
    lateinit var viewModelFactory: MainViewModel.MainViewModelFactory

    private val viewModel: MainViewModel by lazy {
        viewModelFactory.getViewModel(this)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        injectActivity()

        setContentView(R.layout.activity_main)
        setSupportActionBar(toolbar)

        val toggle = ActionBarDrawerToggle(
            this, drawer_layout, toolbar,
            R.string.navigation_drawer_open,
            R.string.navigation_drawer_close
        )
        drawer_layout.addDrawerListener(toggle)
        toggle.syncState()

        nav_view.setNavigationItemSelectedListener(this)

        observeViewModel()
        load()
    }

    override fun onBackPressed() {
        if (drawer_layout.isDrawerOpen(GravityCompat.START)) {
            closeDrawer()
        } else {
            super.onBackPressed()
        }
    }

    override fun onCreateOptionsMenu(menu: Menu): Boolean {
        // Inflate the menu; this adds items to the action bar if it is present.
        menuInflater.inflate(R.menu.main, menu)
        return true
    }

    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        return when (item.itemId) {
            R.id.action_settings -> true
            else -> super.onOptionsItemSelected(item)
        }
    }

    override fun onNavigationItemSelected(item: MenuItem): Boolean {
        // Handle navigation view item clicks here.
        when (item.itemId) {
            R.id.nav_home -> viewModel.dispatch(Action.NavItemClick(NavItem.Home))
            R.id.nav_tabs -> viewModel.dispatch(Action.NavItemClick(NavItem.Tabs))
        }
        closeDrawer()
        return true
    }

    private fun closeDrawer() {
        drawer_layout.closeDrawer(GravityCompat.START)
    }

    private fun observeViewModel() {
        viewModel.state().observe(this, Observer<MainViewModel.State> { state ->
            state?.let { renderViewState(it) }
        })
        viewModel.event().observe(this, Observer<MainViewModel.Event> {
            renderViewEvent(it)
        })
    }

    private fun renderViewState(state: MainViewModel.State) {
        val fragmentTransaction = supportFragmentManager.beginTransaction()
        val fragment = when (state.navItem) {
            is NavItem.Home -> HomeFragment()
            is NavItem.Tabs -> TabsFragment()
        }

        fragmentTransaction.replace(R.id.content_fragment, fragment, state.navItem.toString())
        fragmentTransaction.commit()
    }

    private fun renderViewEvent(event: MainViewModel.Event?) {
        when (event) {
            is MainViewModel.Event.CloseNavDrawer -> {
                closeDrawer()
            }
        }
    }

    private fun load() {
        viewModel.dispatch(Action.Load())
    }

    private fun injectActivity() {
        App.appComponent.inject(this)
    }

    sealed class Action {
        class Load(val navItem: NavItem = NavItem.Home) : Action()
        class NavItemClick(val item: NavItem) : Action()
    }

    sealed class NavItem {
        object Home : NavItem()
        object Tabs : NavItem()
    }
}